/* --------------------------------------
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * --------------------------------------
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
import { ValidationRules } from 'aurelia-validation';
export class PersonGenerated {
  firstName;
  lastName;
  age;
  birthday;

  constructor(firstName, lastName, age, birthday) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.age = age;
    this.birthday = birthday;
  }

  static fromObject(srcObj) {
		return Object.assign(new PersonGenerated(), ...srcObj);
	}
}
export const personGeneratedValidationRules = () =>
  ValidationRules
    .ensure('firstName').displayName('First Name').required().minLength(5).maxLength(10).satisfiesRule(string)
    .ensure('lastName').displayName('Last Name').minLength(10).maxLength(20).satisfiesRule(string)
    .ensure('age').displayName('Age').required().min(18).max(60).satisfiesRule(integer)
    .ensure('birthday').displayName('Birthday').required().satisfiesRule(date);

personValidationRules().on(PersonGenerated);
